pipeline {
  agent none
  options {
    durabilityHint("PERFORMANCE_OPTIMIZED")
    timeout(time: 3, unit: "DAYS")
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }
  stages {
    stage("Checkout") {
      agent {
        node {
          label 'default'
        }      
      steps {
        checkout([$class: "GitSCM", 
          branches: [[name: "${branchName}"]], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [], 
          submoduleCfg: [], 
          userRemoteConfigs: [[credentialsId: "${gitCredentials}", url: "${repoUrl}"]]]
        )
      }
    }
    stage("Build") {
      agent {
        node {
          label 'default'
        }
      steps {
        sh "./gradlew clean build"
      }
    }    
  }
}    
}
