pipeline {
  agent none
  options {
    durabilityHint("PERFORMANCE_OPTIMIZED")
    timeout(time: 3, unit: "DAYS")
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }
  stages {
    stage("Checkout") {
      agent {
        node {
          label 'default'
        }
      }
      steps {
        checkout([$class: "GitSCM", 
          branches: [[name: "${branchName}"]], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [], 
          submoduleCfg: [], 
          userRemoteConfigs: [[credentialsId: "${gitCredentials}", url: "${repoUrl}"]]]
        )
      }
    }
    stage("Build") {
      agent {
        node {
          label 'default'
        }
      }
      steps {
        sh "echo gradlew clean build"
        sh "env"
        sh "echo *****************************************"
        sh "echo"
        sh "which javac"
        sh "java -version"
        sh "which maven"
        sh "echo *****************************************"        
      }
    }    
  }
}
