pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: gradle
            image: gradle:jdk11-alpine
            command:
            - cat
            tty: true
        '''
    }
  }
  options {
    durabilityHint("PERFORMANCE_OPTIMIZED")
    timeout(time: 3, unit: "DAYS")
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }  
  stages {
    stage("Checkout and Build") {
      steps {
          checkout([$class: "GitSCM", 
            branches: [[name: "${branchName}"]], 
            doGenerateSubmoduleConfigurations: false, 
            extensions: [], 
            submoduleCfg: [], 
            userRemoteConfigs: [[credentialsId: "${gitCredentials}", url: "${repoUrl}"]]]
          )
        container('gradle') {
         sh "env"
         sh "ls -R /opt/gradle"
         sh "pwd"
         sh "ls -R /home/gradle"
         sh "gradlew clean build"
        }
      }
    }    
  }
}
